services:
  - type: web
    name: article-generator
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: GOOGLE_AI_MODEL
        value: gemini-2.5-flash
